[package]
name = "rmz"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Fast rm provides an alternative to rm that focuses on maximizing performance."
repository.workspace = true
keywords = ["tools", "files", "rm"]
categories = ["command-line-utilities", "development-tools", "filesystem"]
license.workspace = true

[dependencies]
clap = { version = "4.0.23", features = ["derive", "wrap_help"] }
clap-verbosity-flag = "2.0.0"
error-stack = "0.2.4"
fuc_engine = { version = "0.1.0", path = "../fuc_engine" }
thiserror = "1.0.37"

[dev-dependencies]
criterion = "0.4.0"
expect-test = "1.4.0"
ftzz = "1.1.3"
tempfile = "3.3.0"
trycmd = "0.14.4"
rayon_rm = { path = "../comparisons/rayon_rm" }
og_crappy_rm = { path = "../comparisons/og_crappy_rm" }
stdlib_rm = { path = "../comparisons/stdlib_rm" }

[[bench]]
name = "rmz"
harness = false
