[package]
name = "rmz"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Fast rm provides an alternative to rm that focuses on maximizing performance."
repository.workspace = true
keywords = ["tools", "files", "rm"]
categories = ["command-line-utilities", "development-tools", "filesystem"]
license.workspace = true

[dependencies]
clap = { version = "4.4.11", features = ["derive", "wrap_help"] }
error-stack = "0.4.1"
fuc_engine = { version = "1", path = "../fuc_engine" }
thiserror = "1.0.50"

[dev-dependencies]
criterion = "0.5.1"
ftzz = "2.0.3"
tempfile = "3.8.1"
trycmd = "0.14.19"
rm_rayon = { path = "../comparisons/rm_rayon" }
rm_og_crappy = { path = "../comparisons/rm_og_crappy" }
supercilex-tests = { version = "0.4.2", default-features = false, features = ["clap"] }
remove_dir_all = "0.8.2"
io-adapters = "0.1.0"

[[bench]]
name = "rmz"
harness = false
