[package]
name = "rmz"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Fast rm provides an alternative to rm that focuses on maximizing performance."
repository.workspace = true
keywords = ["tools", "files", "rm"]
categories = ["command-line-utilities", "development-tools", "filesystem"]
license.workspace = true

[dependencies]
clap = { version = "4.0.11", features = ["derive", "wrap_help"] }
clap-verbosity-flag = "2.0.0"
error-stack = "0.2.2"
fuc_engine = { version = "0.1.0", path = "../fuc_engine" }
thiserror = "1.0.37"

[dev-dependencies]
criterion = "0.4.0"
ftzz = "1.1.3"
futures = "0.3.24"
goldenfile = "1.4.3"
tempfile = "3.3.0"
tokio = { version = "1.21.2", features = ["rt"] }
trycmd = "0.14.0"

[[bench]]
name = "rmz"
harness = false
