[package]
name = "cpz"
version = "0.1.0"
authors = ["Alex Saveau <saveau.alexandre@gmail.com>"]
edition = "2021"
description = "Fast cp provides an alternative to cp that focuses on maximizing performance."
repository = "https://github.com/SUPERCILEX/fuc"
keywords = ["tools", "files", "cp"]
categories = ["command-line-utilities", "development-tools", "filesystem"]
license = "Apache-2.0"

[dev-dependencies]
cache-size = "0.5.1"
criterion = "0.3.5"
memmap2 = "0.5.0"
nix = "0.23.0"
num_cpus = "1.13.0"
rand = "0.8.4"
tempfile = "3.2.0"

[[bench]]
name = "copy_methods"
harness = false
