[package]
name = "cpz"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Fast cp provides an alternative to cp that focuses on maximizing performance."
repository.workspace = true
keywords = ["tools", "files", "cp"]
categories = ["command-line-utilities", "development-tools", "filesystem"]
license.workspace = true

[dev-dependencies]
cache-size = "0.6.0"
criterion = "0.4.0"
memmap2 = "0.5.8"
nix = "0.26.1"
rand = "0.8.5"
rustix = { version = "0.36.5", features = ["fs"] }
tempfile = "3.3.0"

[[bench]]
name = "copy_methods"
harness = false
