[package]
name = "cpz"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Fast cp provides an alternative to cp that focuses on maximizing performance."
repository.workspace = true
keywords = ["tools", "files", "cp"]
categories = ["command-line-utilities", "development-tools", "filesystem"]
license.workspace = true

[dependencies]
clap2 = { version = "4.0.32", features = ["derive", "wrap_help"] }
error-stack = "0.2.4"
fuc_engine = { version = "1.0.0", path = "../fuc_engine" }
thiserror = "1.0.38"

[dev-dependencies]
cache-size = "0.6.0"
criterion = "0.4.0"
memmap2 = "0.5.8"
rand = "0.8.5"
supercilex-tests = "0.2.1"
tempfile = "3.3.0"
trycmd = "0.14.8"

[target.'cfg(unix)'.dev-dependencies]
rustix = { version = "0.36.6", features = ["fs"] }

[[bench]]
name = "copy_methods"
harness = false
