[package]
name = "fuc_engine"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Engine for the FUCing project."
repository.workspace = true
keywords = ["tools", "files"]
categories = ["filesystem"]
license.workspace = true

[dependencies]
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["rt", "sync"] }
typed-builder = "0.10.0"

[dev-dependencies]
ftzz = "1.1.3"
goldenfile = "1.4.3"
public-api = "0.20.0"
rstest = "0.15.0"
rustdoc-json = "0.4.1"
tempfile = "3.3.0"
