[package]
name = "fuc_engine"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Engine for the FUCing project."
repository.workspace = true
keywords = ["tools", "files"]
categories = ["filesystem"]
license.workspace = true

[dependencies]
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["rt", "sync"] }
typed-builder = "0.11.0"

[target.'cfg(unix)'.dependencies]
rustix = { version = "0.36.3", features = ["fs"], git = "https://github.com/bytecodealliance/rustix" }

[dev-dependencies]
expect-test = "1.4.0"
ftzz = "1.1.3"
public-api = "0.22.0"
rstest = "0.15.0"
rustdoc-json = "0.6.0"
tempfile = "3.3.0"
