[package]
name = "fuc_engine"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Engine for the FUCing project."
repository.workspace = true
keywords = ["tools", "files"]
categories = ["filesystem"]
license.workspace = true

[dependencies]
lockness = "0.0.1"
thiserror = "1.0.38"
tokio = { version = "1.23.0", features = ["rt", "sync"] }
typed-builder = "0.11.0"

[target.'cfg(unix)'.dependencies]
rustix = { version = "0.36.3", features = ["fs"], git = "https://github.com/bytecodealliance/rustix" }

[dev-dependencies]
expect-test = "1.4.0"
ftzz = "1.1.4"
public-api = "0.24.2"
rstest = "0.16.0"
rustdoc-json = "0.7.3"
tempfile = "3.3.0"
