[package]
name = "fuc_engine"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Engine for the FUCing project."
# TODO https://github.com/Enselic/cargo-public-api/pull/254
#repository.workspace = true
repository = "TMP"
keywords = ["tools", "files"]
categories = ["filesystem"]
license.workspace = true

[dependencies]
crossbeam-channel = "0.5.6"
thiserror = "1.0.38"
typed-builder = "0.11.0"

[target.'cfg(target_os = "linux")'.dependencies]
rustix = { version = "0.36.3", features = ["fs"], git = "https://github.com/bytecodealliance/rustix" }

[target.'cfg(not(target_os = "linux"))'.dependencies]
rayon = "1.6.1"

[target.'cfg(not(any(target_os = "linux", target_os = "macos")))'.dependencies]
remove_dir_all = "0.7.0"

[dev-dependencies]
expect-test = "1.4.0"
ftzz = "1.1.4"
public-api = "0.24.2"
rstest = "0.16.0"
rustdoc-json = "0.7.3"
tempfile = "3.3.0"
